language: R
cache: packages

#r_packages:
#    - covr

#after_success: Rscript -e "covr::codecov()"

#before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
#deploy:
#    provider: script
#    script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
#    skip_cleanup: true

